### Crear hábito
POST http://localhost:8080/api/habits
Content-Type: application/json

{
  "name": "",
  "description": "30 minutos de cardio",
  "frequency": "DAILY"
}

### Obtener todos los hábitos
GET http://localhost:8080/api/habits

### Obtener hábito por id
GET http://localhost:8080/api/habits/999

### Eliminar hábito
DELETE http://localhost:8080/api/habits/1

### Actualizar hábito
PUT http://localhost:8080/api/habits/1
Content-Type: application/json

{
  "name": "Hacer ejercicio actualizado",
  "description": "45 minutos de cardio",
  "frequency": "WEEKLY"
}


### Completar un hábito
POST http://localhost:8080/api/habits/1/completions
Content-Type: application/json

{
  "notes": "Me sentí muy bien hoy"
}

### Ver completions de un hábito
GET http://localhost:8080/api/habits/1/completions




### Registrar usuario
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tomi",
  "email": "tomi@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tomi@gmail.com",
  "password": "123456"
}



### Obtener hábitos con token
GET http://localhost:8080/api/habits
Authorization: Bearer








### 1. Registrar usuario
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Tomi",
  "lastName": "Buixa",
  "email": "tomi@gmail.com",
  "password": "123456"
}

###

### 2. Crear hábito con el token del registro
POST http://localhost:8080/api/habits
Content-Type: application/json
Authorization: Bearer
{
  "name": "Hacer ejercicio",
  "description": "30 minutos de cardio",
  "frequency": "DAILY"
}

###

### 3. Listar hábitos — solo los del usuario autenticado
GET http://localhost:8080/api/habits
Authorization: Bearer




### JSON malformado — debería dar 400
POST http://localhost:8080/api/habits
Content-Type: application/json
Authorization: Bearer
{
  "name": "Test"
  "frequency": "DAILY"
}

###

### Frequency inválida — debería dar 400
POST http://localhost:8080/api/habits
Content-Type: application/json
Authorization: Bearer
{
  "name": "Test",
  "frequency": "MENSUAL"
}






### Usuario nuevo
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Admin",
  "email": "nuevo2@gmail.com",
  "password": "123456"
}

###
GET http://localhost:8080/api/admin/users/count
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJudWV2bzJAZ21haWwuY29tIiwiaWF0IjoxNzgxMDgwMjIxLCJleHAiOjE3ODExNjY2MjF9.HVweD1JH3heNb5WhX4unDRPhNS6Hz8EPcoNuv_PdqxzUBZk66XsqvbTmCiKKqJds


### Mismo token, endpoint normal
GET http://localhost:8080/api/habits
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJudWV2b0BnbWFpbC5jb20iLCJpYXQiOjE3ODEwNzk2MDEsImV4cCI6MTc4MTE2NjAwMX0.TG6Ck0G8IDpV7vfsGQw2QLOdnL7_uHNtRsLge_q2FP9FGnCdesHBjunyVa-LNn-e