### Crear hábito
POST http://localhost:8080/api/habits
Content-Type: application/json

{
  "name": "",
  "description": "30 minutos de cardio",
  "frequency": "DAILY"
}

### Obtener todos los hábitos
GET http://localhost:8080/api/habits

### Obtener hábito por id
GET http://localhost:8080/api/habits/999

### Eliminar hábito
DELETE http://localhost:8080/api/habits/1

### Actualizar hábito
PUT http://localhost:8080/api/habits/1
Content-Type: application/json

{
  "name": "Hacer ejercicio actualizado",
  "description": "45 minutos de cardio",
  "frequency": "WEEKLY"
}


### Completar un hábito
POST http://localhost:8080/api/habits/1/completions
Content-Type: application/json

{
  "notes": "Me sentí muy bien hoy"
}

### Ver completions de un hábito
GET http://localhost:8080/api/habits/1/completions